language: zh

pipeline:
- name: JiebaTokenizer
# - name: CRFEntityExtractor
- name: LexicalSyntacticFeaturizer
  features: [
    ["low", "title", "upper"],
    [
      "BOS",
      "EOS",
      "low",
      "prefix5",
      "prefix2",
      "suffix5",
      "suffix3",
      "suffix2",
      "upper",
      "title",
      "digit",
    ],
    ["low", "title", "upper"],
  ]
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
# - name: EmbeddingIntentClassifier
#   epochs: 50
#   loss_type: margin
- name: DucklingHTTPExtractor
  language: zh$core
  url: http://localhost:8000
  dimensions:
  - time
  - duration
  - phone-number
- name: EntitySynonymMapper
# - name: RegexFeaturizer
- name: DIETClassifier
  hidden_layers_sizes:
    text: [256, 128]
  number_of_transformer_layers: 0
  weight_sparsity: 0
  intent_classification: True
  entity_recognition: True
  use_masked_language_model: False
  BILOU_flag: False
  epochs: 300
- name: ResponseSelector
  epochs: 100


policies:
- name: FormPolicy
- name: MappingPolicy
- name: AugmentedMemoizationPolicy
  max_history: 10
# - name: EmbeddingPolicy
- name: TEDPolicy
  max_history: 10
  epochs: 20
  batch_size: [32,64]
- name: TwoStageFallbackPolicy
  core_threshold: 0.3
  nlu_threshold: 0.8
  deny_suggestion_intent_name: "out_of_scope"