language: zh
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
  max_history: 6
- name: KerasPolicy
- name: MappingPolicy
- name: FormPolicy
- name: EmbeddingPolicy
  max_history: 6
  epochs: 20
  batch_size: [32,64]
