language: zh

pipeline:
- name: JiebaTokenizer
- name: DucklingHTTPExtractor
  language: zh$core
  url: http://localhost:8000
  dimensions:
  - time
  - duration
  - phone-number
- name: EntitySynonymMapper
# - name: CountVectorsFeaturizer
#   OOV_token: oov
#   token_pattern: (?u)\b\w+\b
- name: LexicalSyntacticFeaturizer
  features: [
    ["low", "title", "upper"],
    [
      "BOS",
      "EOS",
      "low",
      "prefix5",
      "prefix2",
      "suffix5",
      "suffix3",
      "suffix2",
      "upper",
      "title",
      "digit",
    ],
    ["low", "title", "upper"],
  ]
# - name: RegexFeaturizer
- name: DIETClassifier
  epochs: 300
  number_of_transformer_layers: 0
- name: ResponseSelector
  epochs: 100


policies:
- name: FormPolicy
- name: MappingPolicy
- name: AugmentedMemoizationPolicy
  max_history: 10
- name: TEDPolicy
  max_history: 10
  epochs: 20
  batch_size: [32,64]
- name: TwoStageFallbackPolicy
  core_threshold: 0.3
  nlu_threshold: 0.8
  deny_suggestion_intent_name: "out_of_scope"